### ISSUE TITLE
[BUG] "this" autocompletion eventually stop working

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#107]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.60.0]
* **Extension version:** [v2.2.7]

## Further Information

Enum struct's "this" autocompletion doesn't work past a certain line of code.

## To Reproduce
[test.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/7146515/test.zip)
"this." suggestions are broken from line 198 (marked with a "no suggestion from here!" comment)

## Expected behaviour

Suggestion doesn't break.

## Error messages
```
ERR Cannot read property 'type' of undefined: TypeError: Cannot read property 'type' of undefined
	at t.ItemsRepository.getTypeOfVariable (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.7\dist\extension.js:2:759316)
	at t.ItemsRepository.getCompletions (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.7\dist\extension.js:2:757932)
	at t.Providers.provideCompletionItems (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.7\dist\extension.js:2:777708)
	at $.provideCompletionItems (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:176938)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:197582
	at xe._withAdapter (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:187656)
	at xe.$provideCompletionItems (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:197558)
	at i._doInvokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:13543)
	at i._invokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:13227)
	at i._receiveRequest (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:11838)
	at i._receiveOneMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:10567)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:98:8663
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at l.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15781)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:30187
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at l.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:15781)
	at r._receiveMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:21051)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:17929
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:66:1712)
	at v.acceptChunk (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:13142)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:74:12490
	at Socket.w (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:13350)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Sarrus1** [comment]
Fixed in a31b54574ce26216f03e8b6e058d4a07322fe748
