### ISSUE TITLE
4.2.0 linter becomes not work.

### ISSUE THREAD

**Issue by lin-kksk** [Sarrus1/sourcepawn-vscode#257]
I can't find some error code so i think it should not be post as a bug , but i need some help actually.

I only use this sourcepawn ext , no other sp ext are installed.

Highlight is ok , refrence is ok , every thing is ok , just linter goes on strike.

**Comment by lin-kksk** [comment]
sm version is 1.11-6911
ext version is 4.2.0

**Comment by lin-kksk** [comment]
ok, return to 4.1.4, linter becomes ok.
may be there is some problem about new version?

**Comment by Sarrus1** [comment]
Hi, to see error messages, can you go in `Help>Toggle Dev tools>Console` and paste the output?
Thanks!

**Comment by lin-kksk** [comment]
When i open the ext Introduction page，console show this thing

" Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'nonce-855c0883-2af6-478c-b3f3-063ed669e781'". Either the 'unsafe-inline' keyword, a hash ('sha256-Mh8dqtZwN7OqnhEHGiDB2Yii1wlmffzu8+5kWLiwAKE='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present. "

When i open a .sp file , console show that 

" ERR Illegal argument, contents must be defined: Error: Illegal argument, contents must be defined
	at new ae (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:78:99276)
	at new ae (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:78:86640)
	at Object.provideHover (c:\Users\lin\.vscode\extensions\codeinchinese.englishchinesedictionary-1.1.0\out\src\extension.js:47:24)
	at d.provideHover (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:40587)
	at g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:70391
	at ee._withAdapter (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:67201)
	at ee.$provideHover (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:70367)
	at i._doInvokeHandler (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13689)
	at i._invokeHandler (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13371)
	at i._receiveRequest (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12090)
	at i._receiveOneMessage (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10843)
	at g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8950
	at b.invoke (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at p.deliver (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at v.fire (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at a.fire (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19042)
	at g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
	at b.invoke (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at p.deliver (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at v.fire (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at a.fire (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19042)
	at r._receiveMessage (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23854)
	at g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21224
	at b.invoke (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at p.deliver (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at v.fire (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at v.acceptChunk (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15873)
	at g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15003
	at Socket.d (g:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26763)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)  "

which didn't happen in 4.0.14 version.

I am a novice of github , and i hope this can help you .

**Comment by Sarrus1** [comment]
Thanks for the response!

`(c:\Users\lin.vscode\extensions\codeinchinese.englishchinesedictionary-1.1.0\out\src\extension.js:47:24)`

Try to disable the `English Chinese Dictionary` extension.

**Comment by lin-kksk** [comment]
> 

Thanks , linter works well as usual .
A very nice ext .
