### ISSUE TITLE
spcomp.exe stack, 100% cpu

### ISSUE THREAD

**Issue by Refzlund** [Sarrus1/sourcepawn-vscode#261]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Insider
- **Extension version:** Latest

# Further Information
When working with `methodmaps` my computer started taking off.
![image](https://user-images.githubusercontent.com/21252096/194985196-e54c6dce-403b-471b-94d4-9d3f43ad9568.png)

I don't know the root of the cause, other than `methodmaps` being when it started with repeated compilers.

# To Reproduce

1. Make a `methodmap` entry in your `.sp` code
2. Make some kind of invalid code (?)
3. ```sp
   methodmap HelloThere {
	public native bool 
   }
   ```
4. ![image](https://user-images.githubusercontent.com/21252096/194986610-c7ef1805-8bb5-49f2-8726-6067c63114f4.png)

# Expected behaviour

I would expect the previous ongoing compile to be closed — giving an error — limited to 1-2 compiles at a time, or shutting down the extension host as an error.

# Error messages

These may or may not have occurred when I forced the processes to stop.

```js
[Extension Host] TypeError: Cannot read properties of null (reading 'text')
	at ib (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:440:9234)
	at Sp.walkTree (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:442:714)
	at ed (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:442:86)
	at hb (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:443:90)
	at Timeout._onTimeout (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:442:1718)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7) (at console.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:90:142292))
log.ts:313   ERR Cannot read properties of undefined (reading 'name'): TypeError: Cannot read properties of undefined (reading 'name')
	at nv (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:485:6076)
	at Cd.provideCompletionItems (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:485:11403)
	at K.provideCompletionItems (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:51689)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:76815
	at ne._withAdapter (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:66986)
	at ne.$provideCompletionItems (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:92:76791)
	at i._doInvokeHandler (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:13680)
	at i._invokeHandler (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:13362)
	at i._receiveRequest (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:12081)
	at i._receiveOneMessage (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:10834)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:100:8941
	at p.invoke (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at b.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at c.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19049)
	at c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:17106
	at p.invoke (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at v.deliver (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at b.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at c.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19049)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:116:15146)
	at MessagePortMain.emit (node:events:526:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_process_init:5:364)
13console.ts:137 [Extension Host] TypeError: Cannot read properties of null (reading 'text')
	at ib (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:440:9234)
	at Sp.walkTree (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:442:714)
	at ed (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:442:86)
	at hb (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:443:90)
	at Timeout._onTimeout (c:\Users\yruge\.vscode-insiders\extensions\sarrus.sourcepawn-vscode-4.2.1\dist\spIndex.js:442:1718)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
```

**Comment by dran1x** [comment]
Pretty much the same as #63 I don't think the issue was ever solved. What SourcePawn Compiler version are you currently using for your project though?

**Comment by Refzlund** [comment]
> Pretty much the same as #63 I don't think the issue was ever solved. What SourcePawn Compiler version are you currently using for your project though?

Ah — yes. I'm using the default one provided by the extension at `user/sourcemodAPI`. Can't tell the version. I'll try to work a bit on the compiler that comes with `sourcemod-1.11.0´ and see if it makes a difference.

I do relate to https://github.com/Sarrus1/sourcepawn-vscode/issues/63 statement of
> I suspect that this comes from the linter, which never closes when the compile fails.

I'll let you know if the issue persists.

**Comment by Sarrus1** [comment]
Thanks for reporting this issue.

I had someone reach out to me on Discord a while back with the same issue, which was also resolved by updating the compiler.

> I'll let you know if the issue persists.

👍

**Comment by Refzlund** [comment]
Reoccurs seemingly at random;

![image](https://user-images.githubusercontent.com/21252096/195710210-412b39b6-3824-403c-b756-bd97ff95ab8b.png)

Using `SourcePawn Compiler 1.11.0.6911` via [sourcemod-1.11.0](https://www.sourcemod.net/downloads.php?branch=stable), which I've downloaded and selected via<br>`"sourcepawn.SpcompPath": "C:/Users/username/Documents/MEGA/Gits/csgo-plugins/sourcemod/scripting/spcomp64.exe"` — from VSCode workspace settings; <br>`C:/Users/username/Documents/MEGA/Gits/csgo-plugins/.vscode/settings.json`

**Comment by Sarrus1** [comment]
Fixed in v5 with the use of the LSP.
