### ISSUE TITLE
Eveything I've found with the pre-release 5.0.3 (Keldra)

### ISSUE THREAD

**Issue by ddorab** [Sarrus1/sourcepawn-vscode#281]
# Basic informations

- **OS:** [Windows]
- **VSCode version:** Latest
- **Extension version:** 5.0.3

# Further Information

- No suggestion
![image](https://user-images.githubusercontent.com/45337750/219457023-c3628f43-9472-41ad-9d46-d6248ea970e3.png)

- We talked about this in DMs and it actually did work when I restarted vscode that time but it doesn't seem to anymore (I haven't changed any settings/includes etc.)
![image](https://user-images.githubusercontent.com/45337750/219457129-4990f098-abb6-4ac1-b7d1-9b1ce946c73c.png)

- `sizeof` just so you don't forget

# To Reproduce

I have no idea :D

# Error messages
Didn't notice any errors

> I'll be updating the post continously when I come across new stuff

**Comment by ddorab** [comment]
Everything seems to have gone away, `sizeof`, `continue`, `break` are still missing. They're not that important, simply good to have. Thanks for all the effort.

**Comment by ddorab** [comment]
```
[Info  - 11:59:05 PM] Connection to server got closed. Server will restart.
Starting SourcePawn server
Received config [Object {"includesDirectories": Array [String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\include")], "mainPath": String("c:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\komal\\scripting\\komal.sp"), "spcompPath": String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\spcomp.exe")}]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\semantic_analyzer\resolvers.rs:123:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lsp-server-0.6.0\src\stdio.rs:29:37
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Info  - 11:59:07 PM] Connection to server got closed. Server will restart.
Starting SourcePawn server
Received config [Object {"includesDirectories": Array [String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\include")], "mainPath": String("c:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\komal\\scripting\\komal.sp"), "spcompPath": String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\spcomp.exe")}]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\semantic_analyzer\resolvers.rs:123:18
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lsp-server-0.6.0\src\stdio.rs:29:37
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 11:59:08 PM] The SourcePawn Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
also hello :D

**Comment by Sarrus1** [comment]
Hey thanks again for your feedback :)
Do you think I missed any symbol? https://github.com/Sarrus1/sourcepawn-lsp/commit/ad19619ea05ff5daff84a9c9987788a068fd9b65

**Comment by Sarrus1** [comment]
> ```
> [Info  - 11:59:05 PM] Connection to server got closed. Server will restart.
> Starting SourcePawn server
> Received config [Object {"includesDirectories": Array [String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\include")], "mainPath": String("c:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\komal\\scripting\\komal.sp"), "spcompPath": String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\spcomp.exe")}]
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\semantic_analyzer\resolvers.rs:123:18
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lsp-server-0.6.0\src\stdio.rs:29:37
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Info  - 11:59:07 PM] Connection to server got closed. Server will restart.
> Starting SourcePawn server
> Received config [Object {"includesDirectories": Array [String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\include")], "mainPath": String("c:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\komal\\scripting\\komal.sp"), "spcompPath": String("C:\\Users\\Dora\\Documents\\dev\\csgo\\sm-projects\\spcomp.exe")}]
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\semantic_analyzer\resolvers.rs:123:18
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "SendError(..)"', C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\lsp-server-0.6.0\src\stdio.rs:29:37
> stack backtrace:
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [Error - 11:59:08 PM] The SourcePawn Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
> ```
> 
> also hello :D

Can you please send me the file that caused this? Curious as to why this panicked... I've added a better fail safe in the latest build, which should fix the issue.
