### ISSUE TITLE
Hover fails on dynamic arrays and Struct instances

### ISSUE THREAD

**Issue by Sarrus1** [Sarrus1/sourcepawn-vscode#383]
```
thread 'Worker' panicked at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/hir/src/semantics.rs:164:18:
internal error: entered unreachable code
stack backtrace:
   0:     0x5990d00e3682 - std::backtrace_rs::backtrace::libunwind::trace::he4ee80166a02c846
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1:     0x5990d00e3682 - std::backtrace_rs::backtrace::trace_unsynchronized::h476faccf57e88641
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5990d00e3682 - std::sys_common::backtrace::_print_fmt::h430c922a77e7a59c
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x5990d00e3682 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffecb437d922f988
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5990d01113ec - core::fmt::rt::Argument::fmt::hf3df69369399bfa9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/rt.rs:142:9
   5:     0x5990d01113ec - core::fmt::write::hd9a8d7d029f9ea1a
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/fmt/mod.rs:1153:17
   6:     0x5990d00dff8f - std::io::Write::write_fmt::h0e1226b2b8d973fe
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/io/mod.rs:1843:15
   7:     0x5990d00e3454 - std::sys_common::backtrace::_print::hd2df4a083f6e69b8
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5990d00e3454 - std::sys_common::backtrace::print::he907f6ad7eee41cb
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5990d00e4ffb - std::panicking::default_hook::{{closure}}::h3926193b61c9ca9b
  10:     0x5990d00e4d53 - std::panicking::default_hook::h25ba2457dea68e65
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:292:9
  11:     0x5990cfeec874 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::hb56d6207bc7c5eee
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
  12:     0x5990cfeec874 - stdx::panic_context::PanicContext::init::{{closure}}::{{closure}}::h583ebea7f0e533b4
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/panic_context.rs:31:17
  13:     0x5990cfeec874 - stdx::panic_context::with_ctx::{{closure}}::h67057e5f73f92263
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/panic_context.rs:48:20
  14:     0x5990cfeec874 - std::thread::local::LocalKey<T>::try_with::h6258b3304cf9f68c
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:284:16
  15:     0x5990cfeec874 - std::thread::local::LocalKey<T>::with::h59c2abb143e6b391
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/local.rs:260:9
  16:     0x5990cfeec874 - stdx::panic_context::with_ctx::hca5841cf8cfab3ef
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/panic_context.rs:48:9
  17:     0x5990cfeec874 - stdx::panic_context::PanicContext::init::{{closure}}::h3d497e5f9af2d848
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/panic_context.rs:24:13
  18:     0x5990d00e5630 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h022ca2c0d8c21c9e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
  19:     0x5990d00e5630 - std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
  20:     0x5990d00e5339 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:649:13
  21:     0x5990d00e3b56 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
  22:     0x5990d00e50a4 - rust_begin_unwind
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
  23:     0x5990cf6a3ef5 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
  24:     0x5990cf6a3fb3 - core::panicking::panic::h8ddd58dc57c2dc00
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:145:5
  25:     0x5990cfd6c1e6 - hir::semantics::Semantics<DB>::find_def::h23c1958e9234a7b7
  26:     0x5990cfd4ee3f - ide::hover::hover::h7aa24ec61b74cfa0
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/ide/src/hover.rs:117:15
  27:     0x5990cfd4a353 - ide::Analysis::hover::{{closure}}::h3e41d225e7c96bff
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/ide/src/lib.rs:215:27
  28:     0x5990cfd4a353 - ide::Analysis::with_db::{{closure}}::hd0a9f7222a757e7b
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/ide/src/lib.rs:188:29
  29:     0x5990cfd4a353 - std::panicking::try::do_call::h3b5445f67e564b81
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  30:     0x5990cfd4a353 - std::panicking::try::h4f9ce0b7ad6a1edb
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  31:     0x5990cfd4a353 - std::panic::catch_unwind::hb9072de395b551c9
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  32:     0x5990cfd4a353 - salsa::Cancelled::catch::h6fd287b8161332cb
                               at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/salsa-0.17.0-pre.2/src/lib.rs:586:15
  33:     0x5990cfd4a353 - ide::Analysis::with_db::h79d8ec10357be58f
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/ide/src/lib.rs:188:9
  34:     0x5990cfd4a353 - ide::Analysis::hover::he36bcc645eb0b705
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/ide/src/lib.rs:215:14
  35:     0x5990cfc96329 - sourcepawn_lsp::handlers::request::handle_hover::hc337f44dc1152413
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/sourcepawn_lsp/src/handlers/request.rs:124:22
  36:     0x5990cfcca31f - sourcepawn_lsp::dispatch::RequestDispatcher::on_with_thread_intent::{{closure}}::{{closure}}::h3736c327807e0faa
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/sourcepawn_lsp/src/dispatch.rs:102:17
  37:     0x5990cfcca31f - std::panicking::try::do_call::hfa28a2adfdcb8d0e
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  38:     0x5990cfcca31f - std::panicking::try::h4b08d379682e1cff
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  39:     0x5990cfc5ae54 - std::panic::catch_unwind::hecca3d1318c5df2d
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  40:     0x5990cfc5ae54 - sourcepawn_lsp::dispatch::RequestDispatcher::on_with_thread_intent::{{closure}}::ha35219a4cdad9457
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/sourcepawn_lsp/src/dispatch.rs:100:26
  41:     0x5990cfc5ae54 - sourcepawn_lsp::task_pool::TaskPool<T>::spawn::{{closure}}::hb2dff71fadb378f2
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/sourcepawn_lsp/src/task_pool.rs:27:33
  42:     0x5990cfc5ae54 - stdx::thread::pool::Pool::spawn::{{closure}}::h0c65eeaac8cb1ce8
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/thread/pool.rs:86:13
  43:     0x5990cfc5ae54 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb1c448b88a62b7a3
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  44:     0x5990cfeeda36 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hab106628e811be0f
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2020:9
  45:     0x5990cfeeda36 - stdx::thread::pool::Pool::new::{{closure}}::hbf0dee2e1a441397
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/thread/pool.rs:61:29
  46:     0x5990cfeeda36 - stdx::thread::Builder::spawn::{{closure}}::hb8e791cd5b562a07
                               at /home/runner/work/sourcepawn-vscode/sourcepawn-vscode/crates/stdx/src/thread.rs:81:13
  47:     0x5990cfeeda36 - std::sys_common::backtrace::__rust_begin_short_backtrace::h29b269dddb55ac38
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  48:     0x5990cfeef670 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hf0016d1d73fb8769
                               at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/thread/mod.rs:528:17
  49:     0x5990cfeef670 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h5f5de60de76d136b
... (23lignes restantes)
```

**Comment by Sarrus1** [comment]
This has been fixed
