### ISSUE TITLE
[BUG] Methods are not appearing in autocompletion

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#95]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.1]
* **Extension version:** [v2.2.3]

## Further Information

Example: 
[bug2.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/7039887/bug2.zip)
`PushArray` method (or any method) does not appear in autocompletion.

## Expected behaviour

Methods appear in autocompletion.

## Error messages

```
[Extension Host] file://__sourcemod_builtin/sourcemod.inc
console.ts:137 [Extension Host] file://__sourcemod_builtin/sdktools.inc
console.ts:137 [Extension Host] file://__sourcemod_builtin/cstrike.inc
console.ts:137 [Extension Host] file:///c%3A/Users/zer0.k/Desktop/begone/bug2/include/movement.inc
console.ts:137 [Extension Host] file:///c%3A/Users/zer0.k/Desktop/begone/bug2/include/bug.inc
2console.ts:137 [Extension Host] file://__sourcemod_builtin/sourcemod.inc
console.ts:137 [Extension Host] file://__sourcemod_builtin/sdktools.inc
console.ts:137 [Extension Host] file://__sourcemod_builtin/cstrike.inc
console.ts:137 [Extension Host] file:///c%3A/Users/zer0.k/Desktop/begone/bug2/include/movement.inc
console.ts:137 [Extension Host] file:///c%3A/Users/zer0.k/Desktop/begone/bug2/include/bug.inc
log.ts:301   ERR Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
	at Object.t.getSignatureAttributes (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.3\dist\extension.js:2:780147)
	at t.Providers.provideSignatureHelp (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.3\dist\extension.js:2:777346)
	at q.provideSignatureHelp (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:178805)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:196680
	at We._withAdapter (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:185649)
	at We.$provideSignatureHelp (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:196656)
	at h._doInvokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
	at h._receiveOneMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
log.ts:301   ERR i.calls is not iterable: TypeError: i.calls is not iterable
	at t.Providers.provideDocumentSemanticTokens (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.3\dist\extension.js:2:778875)
	at x.provideDocumentSemanticTokens (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:172409)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:194523
	at We._withAdapter (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:185649)
	at We.$provideDocumentSemanticTokens (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:194501)
	at h._doInvokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
	at h._receiveOneMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Sarrus1** [comment]
This works in 2.2.4
