### ISSUE TITLE
[BUG] Enum struct suggestion does not work on secondary files

### ISSUE THREAD

**Issue by zer0k-z** [Sarrus1/sourcepawn-vscode#98]
## Basic info

* **OS:** [Windows]
* **VSCode version:** [v1.59.1]
* **Extension version:** [v2.2.4]

## Further Information

Autocompletion/suggestion does not appear on enum structs in secondary files.

## To Reproduce

Example: [bug2.zip](https://github.com/Sarrus1/sourcepawn-vscode/files/7058942/bug2.zip)
Set `bug2.sp` as main, functions in `second.sp` are not suggested.

## Expected behaviour

Autocompletion/suggestion works in secondary files.

## Error messages
```
  ERR Cannot read property 'type' of undefined: TypeError: Cannot read property 'type' of undefined
	at t.ItemsRepository.getTypeOfVariable (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.4\dist\extension.js:2:758969)
	at t.ItemsRepository.getCompletions (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.4\dist\extension.js:2:757585)
	at t.Providers.provideCompletionItems (c:\Users\zer0.k\.vscode\extensions\sarrus.sourcepawn-vscode-2.2.4\dist\extension.js:2:777232)
	at z.provideCompletionItems (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:175191)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:195478
	at We._withAdapter (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:185649)
	at We.$provideCompletionItems (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:195454)
	at h._doInvokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12819)
	at h._invokeHandler (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:12503)
	at h._receiveRequest (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:11107)
	at h._receiveOneMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9943)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8039
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:30060
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at c.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15825)
	at r._receiveMessage (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21091)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17969
	at d.fire (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1712)
	at v.acceptChunk (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13186)
	at c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12534
	at Socket.w (c:\Users\zer0.k\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by Sarrus1** [comment]
I can't reproduce this issue with your sample.
I get autocompletion from bug2.sp and second.sp.
There are no missing functions. Are you sure this is with 2.2.4?
